topics:
  -
    topic: /ardrone/image_raw  # Topic name on both ROS 1 and ROS 2
    type: sensor_msgs/msg/Image  # Type of topic to bridge
    queue_size: 10  # Queue size
  # -
  #   topic: /ardrone/camera_info  # Topic name on both ROS 1 and ROS 2
  #   type: sensor_msgs/msg/CameraInfo  # Type of topic to bridge
  #   queue_size: 10  # Queue size
  -
    topic: /ardrone/imu  # Topic name on both ROS 1 and ROS 2
    type: sensor_msgs/msg/Imu  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /ardrone/motors  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Int16MultiArray  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /ardrone/cmd_vel  # Topic name on both ROS 1 and ROS 2
    type: geometry_msgs/msg/Twist  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /ardrone/takeoff  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Empty  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /ardrone/land  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Empty  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /ardrone/reset  # Topic name on both ROS 1 and ROS 2
    type: std_msgs/msg/Empty  # Type of topic to bridge
    queue_size: 10  # Queue size
  -
    topic: /quadrotor_pose
    type: geometry_msgs/msg/PoseStamped
    queue_size: 10
  -
    topic: /quadrotor_twist
    type: geometry_msgs/msg/TwistStamped
    queue_size: 10
  -
    topic: /mocap
    type: geometry_msgs/msg/PointStamped
    queue_size: 10
